name: Automated Test

on:
  push:
  workflow_dispatch:

jobs:
  api-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verify Python installation
        run: python --version

      - name: Run CI Python script
        run: python cicd/smoketest.py